defmodule FnbErp.Repo.Migrations.InitialErp do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stock_movements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :quantity, :decimal, null: false, precision: 14, scale: 3
      add :reason, :text, null: false
      add :reference, :text

      add :occurred_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inventory_id, :uuid, null: false
    end

    create table(:products, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :sku, :text, null: false
      add :description, :text
      add :unit_price, :decimal, null: false, precision: 14, scale: 2
      add :unit_of_measure, :text, null: false, default: "pcs"
      add :category, :text, null: false, default: "finished_good"
      add :active?, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:products, [:sku], name: "products_unique_sku_index")

    create table(:orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :order_number, :text, null: false
      add :order_date, :date, null: false, default: fragment("CURRENT_DATE")
      add :status, :text, null: false, default: "draft"
      add :tax_rate, :decimal, null: false, default: "0.11", precision: 5, scale: 4
      add :notes, :text
      add :cancellation_reason, :text
      add :confirmed_at, :utc_datetime_usec
      add :fulfilled_at, :utc_datetime_usec
      add :paid_at, :utc_datetime_usec
      add :cancelled_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id, :uuid, null: false
      add :location_id, :uuid, null: false
    end

    create unique_index(:orders, [:order_number], name: "orders_unique_order_number_index")

    create table(:order_lines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :quantity, :decimal, null: false, precision: 14, scale: 3
      add :unit_price, :decimal, precision: 14, scale: 2
      add :subtotal, :decimal, null: false, default: "0", precision: 16, scale: 2

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_id,
          references(:orders,
            column: :id,
            name: "order_lines_order_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :product_id,
          references(:products,
            column: :id,
            name: "order_lines_product_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:order_lines, [:order_id, :product_id],
             name: "order_lines_unique_product_per_order_index"
           )

    create table(:locations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :code, :text, null: false
      add :address, :text
      add :active?, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:locations, [:code], name: "locations_unique_code_index")

    create table(:inventories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:stock_movements) do
      modify :inventory_id,
             references(:inventories,
               column: :id,
               name: "stock_movements_inventory_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:inventories) do
      add :quantity_on_hand, :decimal, null: false, default: "0", precision: 14, scale: 3

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :product_id,
          references(:products,
            column: :id,
            name: "inventories_product_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :location_id,
          references(:locations,
            column: :id,
            name: "inventories_location_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:inventories, [:product_id, :location_id],
             name: "inventories_unique_product_location_index"
           )

    create table(:customers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:orders) do
      modify :customer_id,
             references(:customers,
               column: :id,
               name: "orders_customer_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :location_id,
             references(:locations,
               column: :id,
               name: "orders_location_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:customers) do
      add :name, :text, null: false
      add :contact_name, :text
      add :email, :text
      add :phone, :text
      add :address_line1, :text
      add :address_line2, :text
      add :city, :text
      add :province, :text
      add :postal_code, :text
      add :country, :text, default: "ID"
      add :active?, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:customers, [:email], name: "customers_unique_email_index")

    create constraint(:inventories, :inventories_quantity_on_hand_non_negative,
             check: """
               quantity_on_hand >= 0
             """
           )

    execute("""
    CREATE SEQUENCE IF NOT EXISTS order_number_seq
    """)
  end

  def down do
    execute("""
    DROP SEQUENCE IF EXISTS order_number_seq
    """)

    drop_if_exists constraint(:inventories, :inventories_quantity_on_hand_non_negative)

    drop_if_exists unique_index(:customers, [:email], name: "customers_unique_email_index")

    alter table(:customers) do
      remove :updated_at
      remove :inserted_at
      remove :active?
      remove :country
      remove :postal_code
      remove :province
      remove :city
      remove :address_line2
      remove :address_line1
      remove :phone
      remove :email
      remove :contact_name
      remove :name
    end

    drop constraint(:orders, "orders_customer_id_fkey")

    drop constraint(:orders, "orders_location_id_fkey")

    alter table(:orders) do
      modify :location_id, :uuid
      modify :customer_id, :uuid
    end

    drop table(:customers)

    drop constraint(:inventories, "inventories_product_id_fkey")

    drop constraint(:inventories, "inventories_location_id_fkey")

    drop_if_exists unique_index(:inventories, [:product_id, :location_id],
                     name: "inventories_unique_product_location_index"
                   )

    alter table(:inventories) do
      remove :location_id
      remove :product_id
      remove :updated_at
      remove :inserted_at
      remove :quantity_on_hand
    end

    drop constraint(:stock_movements, "stock_movements_inventory_id_fkey")

    alter table(:stock_movements) do
      modify :inventory_id, :uuid
    end

    drop table(:inventories)

    drop_if_exists unique_index(:locations, [:code], name: "locations_unique_code_index")

    drop table(:locations)

    drop constraint(:order_lines, "order_lines_order_id_fkey")

    drop constraint(:order_lines, "order_lines_product_id_fkey")

    drop_if_exists unique_index(:order_lines, [:order_id, :product_id],
                     name: "order_lines_unique_product_per_order_index"
                   )

    drop table(:order_lines)

    drop_if_exists unique_index(:orders, [:order_number],
                     name: "orders_unique_order_number_index"
                   )

    drop table(:orders)

    drop_if_exists unique_index(:products, [:sku], name: "products_unique_sku_index")

    drop table(:products)

    drop table(:stock_movements)
  end
end
