defmodule FnbErp.Repo.Migrations.IndexStockMovementsInventoryId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:stock_movements, [:inventory_id])
  end

  def down do
    drop_if_exists index(:stock_movements, [:inventory_id])
  end
end
